
import type { Language, InsuranceProduct, InsuranceProductSummary, SavingsAccount, SavingsTransaction, DistributionDataPoint, PolicyClaimInfo } from './types';

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'hinglish', name: 'Hinglish' },
  { code: 'mr', name: 'मराठी' },
  { code: 'gu', name: 'ગુજરાતી' },
  { code: 'bn', name: 'বাংলা' },
  { code: 'te', name: 'తెలుగు' },
  { code: 'ta', name: 'தமிழ்' },
  { code: 'kn', name: 'ಕನ್ನಡ' },
  { code: 'or', name: 'ଓଡ଼ିଆ' },
];

export const SAVINGS_AMOUNTS = [5, 10, 20, 50, 100, 500];

export const VEO_LOADING_MESSAGES = [
    "Crafting your visual story...",
    "Gathering pixels from the digital universe...",
    "This is where the magic happens. Please wait.",
    "Your video is being generated by our AI director.",
    "Just a few more moments...",
    "Rendering high-definition visuals...",
];

export const INSURANCE_PRODUCTS: InsuranceProduct[] = [
  {
    id: 1,
    productNameKey: 'policy.1.productName',
    header: { icons: ['ShieldCheckIcon', 'BoltIcon'], titleKey: 'policy.1.header.title', subtextKey: 'policy.1.header.subtext' },
    video: { 
      titleKey: 'policy.1.video.title',
      script: [ 'policy.1.video.script.1', 'policy.1.video.script.2', 'policy.1.video.script.3' ],
      url: 'https://streamable.com/e/edyyg0?autoplay=0'
    },
    coverage: {
      summary: [ { key: 'policy.1.coverage.summary.death', value: '₹1,00,000' }, { key: 'policy.1.coverage.summary.disability', value: 'Severity Based' }, { key: 'policy.1.coverage.summary.hospitalCash', value: '₹500/day' } ],
      notCovered: ['policy.1.coverage.notCovered.alcohol', 'policy.1.coverage.notCovered.selfHarm'],
    },
    benefits: ['policy.1.benefits.b1', 'policy.1.benefits.b2', 'policy.1.benefits.b3'],
    roiGraph: {
      titleKey: 'policy.1.roiGraph.title', xAxisKey: 'policy.1.roiGraph.xAxis', yAxisKey: 'policy.1.roiGraph.yAxis',
      type: 'bar',
      legend: { premium: 'policy.1.roiGraph.legend.premium', coverage: 'policy.1.roiGraph.legend.coverage' },
      data: [
        { label: '1 Year', stacks: { premium: 3650, coverage: 100000 }, roi: 27.4 },
        { label: '2 Years', stacks: { premium: 7300, coverage: 100000 }, roi: 13.7 },
        { label: '3 Years', stacks: { premium: 10950, coverage: 100000 }, roi: 9.1 }
      ]
    },
    eligibility: ['policy.1.eligibility.target'],
    cta: { textKey: 'policy.1.cta.text' },
    tags: ['Popular', 'Daily']
  },
  {
    id: 2,
    productNameKey: 'policy.2.productName',
    header: { icons: ['HeartIcon', 'UsersIcon'], titleKey: 'policy.2.header.title', subtextKey: 'policy.2.header.subtext' },
    video: { 
      titleKey: 'policy.2.video.title',
      script: [ 'policy.2.video.script.1', 'policy.2.video.script.2', 'policy.2.video.script.3' ],
      url: 'https://streamable.com/e/93kefn?autoplay=0'
    },
    coverage: {
      summary: [ { key: 'policy.2.coverage.summary.hospitalization', value: '₹50,000' }, { key: 'policy.2.coverage.summary.prePost', value: '15/30 Days' }, { key: 'policy.2.coverage.summary.dayCare', value: 'Included' } ],
      notCovered: ['policy.2.coverage.notCovered.cosmetic'],
    },
    benefits: ['policy.2.benefits.b1', 'policy.2.benefits.b2', 'policy.2.benefits.b3'],
    roiGraph: {
      titleKey: 'policy.2.roiGraph.title', xAxisKey: 'policy.2.roiGraph.xAxis', yAxisKey: 'policy.2.roiGraph.yAxis',
      type: 'bar',
      legend: { premium: 'policy.1.roiGraph.legend.premium', coverage: 'policy.1.roiGraph.legend.coverage' },
      data: [
        { label: '1 Year', stacks: { premium: 1200, coverage: 50000 }, roi: 41.6 },
        { label: '2 Years', stacks: { premium: 2400, coverage: 50000 }, roi: 20.8 },
        { label: '3 Years', stacks: { premium: 3600, coverage: 50000 }, roi: 13.8 }
      ]
    },
    eligibility: ['policy.2.eligibility.target'],
    cta: { textKey: 'policy.2.cta.text' },
    tags: ['Family', 'Health']
  },
  {
    id: 3,
    productNameKey: 'policy.3.productName',
    header: { icons: ['GlobeAltIcon', 'SunIcon'], titleKey: 'policy.3.header.title', subtextKey: 'policy.3.header.subtext' },
    video: { 
      titleKey: 'policy.3.video.title',
      script: [ 'policy.3.video.script.1', 'policy.3.video.script.2', 'policy.3.video.script.3' ],
      url: 'https://streamable.com/e/4008ax?autoplay=0'
    },
    coverage: {
      summary: [ { key: 'policy.3.coverage.summary.pest', value: 'Infestation' }, { key: 'policy.3.coverage.summary.weather', value: 'Rain/Hail' }, { key: 'policy.3.coverage.summary.nonSeasonal', value: 'Fire/Accident' } ],
      notCovered: ['policy.3.coverage.notCovered.intentional'],
    },
    benefits: ['policy.3.benefits.b1', 'policy.3.benefits.b2', 'policy.3.benefits.b3'],
    roiGraph: {
      titleKey: 'policy.3.roiGraph.title', xAxisKey: 'policy.3.roiGraph.xAxis', yAxisKey: 'policy.3.roiGraph.yAxis',
      type: 'bar',
      legend: { premium: 'policy.1.roiGraph.legend.premium', coverage: 'policy.1.roiGraph.legend.coverage' },
      data: [
        { label: '1 Year', stacks: { premium: 100, coverage: 5000 }, roi: 50 },
        { label: '2 Years', stacks: { premium: 200, coverage: 5000 }, roi: 25 },
        { label: '3 Years', stacks: { premium: 300, coverage: 5000 }, roi: 16.6 }
      ]
    },
    eligibility: ['policy.3.eligibility.target'],
    cta: { textKey: 'policy.3.cta.text' },
    tags: ['Farming', 'Seasonal']
  },
  {
    id: 6,
    productNameKey: 'policy.6.productName',
    header: { icons: ['UsersIcon', 'ShieldCheckIcon'], titleKey: 'policy.6.header.title', subtextKey: 'policy.6.header.subtext' },
    video: {
      titleKey: 'policy.6.video.title',
      script: [ 'policy.6.video.script.1', 'policy.6.video.script.2', 'policy.6.video.script.3' ],
      url: 'https://streamable.com/e/kedwzj?autoplay=0'
    },
    coverage: {
      summary: [ { key: 'policy.6.coverage.summary.natural', value: 'Natural Death' }, { key: 'policy.6.coverage.summary.accidental', value: 'Accidental Death' }, { key: 'policy.6.coverage.summary.terminal', value: 'Illness Rider' } ],
      notCovered: ['policy.6.coverage.notCovered.suicide'],
    },
    benefits: ['policy.6.benefits.b1', 'policy.6.benefits.b2', 'policy.6.benefits.b3'],
    roiGraph: {
      titleKey: 'policy.6.roiGraph.title', xAxisKey: 'policy.6.roiGraph.xAxis', yAxisKey: 'policy.6.roiGraph.yAxis',
      type: 'bar',
      legend: { premium: 'policy.1.roiGraph.legend.premium', coverage: 'policy.1.roiGraph.legend.coverage' },
      data: [
          { label: '1 Year', stacks: { premium: 600, coverage: 300000 }, roi: 500 },
          { label: '2 Years', stacks: { premium: 1200, coverage: 300000 }, roi: 250 },
          { label: '3 Years', stacks: { premium: 1800, coverage: 300000 }, roi: 166 }
      ]
    },
    eligibility: ['policy.6.eligibility.target'],
    cta: { textKey: 'policy.6.cta.text' },
    tags: ['Life', 'Family']
  },
  {
    id: 8,
    productNameKey: 'policy.8.productName',
    header: { icons: ['BuildingStorefrontIcon', 'ExclamationTriangleIcon'], titleKey: 'policy.8.header.title', subtextKey: 'policy.8.header.subtext' },
    video: {
      titleKey: 'policy.8.video.title',
      script: [ 'policy.8.video.script.1', 'policy.8.video.script.2', 'policy.8.video.script.3' ],
      url: 'https://streamable.com/e/1wualr?autoplay=0'
    },
    coverage: {
      summary: [ { key: 'policy.8.coverage.summary.injury', value: 'Bodily Injury' }, { key: 'policy.8.coverage.summary.property', value: 'Property Damage' }, { key: 'policy.8.coverage.summary.legal', value: 'Legal Costs' } ],
      notCovered: ['policy.8.coverage.notCovered.intentional'],
    },
    benefits: ['policy.8.benefits.b1', 'policy.8.benefits.b2', 'policy.8.benefits.b3'],
    roiGraph: {
      titleKey: 'policy.8.roiGraph.title', xAxisKey: 'policy.8.roiGraph.xAxis', yAxisKey: 'policy.8.roiGraph.yAxis',
      type: 'bar',
      legend: { premium: 'policy.1.roiGraph.legend.premium', coverage: 'policy.1.roiGraph.legend.coverage' },
      data: [
          { label: '1 Year', stacks: { premium: 500, coverage: 100000 }, roi: 200 },
          { label: '2 Years', stacks: { premium: 1000, coverage: 100000 }, roi: 100 },
          { label: '3 Years', stacks: { premium: 1500, coverage: 100000 }, roi: 66.6 }
      ]
    },
    eligibility: ['policy.8.eligibility.target'],
    cta: { textKey: 'policy.8.cta.text' },
    tags: ['Business', 'Liability']
  },
  {
    id: 9,
    productNameKey: 'policy.9.productName',
    header: { icons: ['CurrencyRupeeIcon', 'PlusIcon'], titleKey: 'policy.9.header.title', subtextKey: 'policy.9.header.subtext' },
    video: {
      titleKey: 'policy.9.video.title',
      script: [ 'policy.9.video.script.1', 'policy.9.video.script.2', 'policy.9.video.script.3' ],
      url: 'https://streamable.com/e/mu1p8t?autoplay=0'
    },
    coverage: {
      summary: [ { key: 'policy.9.coverage.summary.hospital', value: '₹1,000/day' }, { key: 'policy.9.coverage.summary.illness', value: 'Lump Sum' }, { key: 'policy.9.coverage.summary.ambulance', value: 'Transport' } ],
      notCovered: ['policy.9.coverage.notCovered.outpatient'],
    },
    benefits: ['policy.9.benefits.b1', 'policy.9.benefits.b2', 'policy.9.benefits.b3'],
    roiGraph: {
      titleKey: 'policy.9.roiGraph.title', xAxisKey: 'policy.9.roiGraph.xAxis', yAxisKey: 'policy.9.roiGraph.yAxis',
      type: 'bar',
      legend: { premium: 'policy.1.roiGraph.legend.premium', coverage: 'policy.1.roiGraph.legend.coverage' },
      data: [
          { label: '1 Year', stacks: { premium: 1200, coverage: 10000 }, roi: 8.3 },
          { label: '2 Years', stacks: { premium: 2400, coverage: 10000 }, roi: 8.3 }, // Benefit usually capped per year
          { label: '3 Years', stacks: { premium: 3600, coverage: 10000 }, roi: 8.3 }
      ]
    },
    eligibility: ['policy.9.eligibility.target'],
    cta: { textKey: 'policy.9.cta.text' },
    tags: ['Senior', 'Care']
  },
];

const PRODUCT_COLORS_MAP: { [key: number]: { bg: string; text: string } } = {
  1: { bg: 'bg-red-100', text: 'text-red-600' },
  2: { bg: 'bg-blue-100', text: 'text-blue-600' },
  3: { bg: 'bg-green-100', text: 'text-green-600' },
  6: { bg: 'bg-teal-100', text: 'text-teal-600' },
  8: { bg: 'bg-pink-100', text: 'text-pink-600' },
  9: { bg: 'bg-yellow-100', text: 'text-yellow-600' },
};

export const INSURANCE_PRODUCTS_SUMMARY: InsuranceProductSummary[] = INSURANCE_PRODUCTS.map(p => ({
  id: p.id,
  productNameKey: p.productNameKey,
  icon: p.header.icons[0] || 'ShieldCheckIcon',
  color: PRODUCT_COLORS_MAP[p.id] || { bg: 'bg-gray-100', text: 'text-gray-600' },
}));


// --- Savings Feature Mock Data ---

export const SAVINGS_ACCOUNTS: SavingsAccount[] = [
    { id: 'emergency', type: 'emergency', titleKey: 'save.home.emergencyFund', balance: 4800, goal: 12000, planActive: false },
    { id: 'daily', type: 'daily', titleKey: 'save.home.dailyJar', balance: 650, goal: 2000, planActive: true },
    { id: 'goal', type: 'goal', titleKey: 'save.home.goals', balance: 1200, goal: 5000, planActive: false },
];

export const SAVINGS_TRANSACTIONS: SavingsTransaction[] = [
    { id: 1, accountId: 'emergency', description: 'Auto-save', amount: 20, date: 'Today', type: 'deposit' },
    { id: 2, accountId: 'daily', description: 'Round-up', amount: 8, date: 'Today', type: 'round-up' },
    { id: 3, accountId: 'daily', description: 'Quick save', amount: 50, date: 'Yesterday', type: 'deposit' },
    { id: 4, accountId: 'emergency', description: 'Manual Top-up', amount: 100, date: '2 days ago', type: 'deposit' },
    { id: 5, accountId: 'daily', description: 'Round-up', amount: 12, date: '2 days ago', type: 'round-up' },
    { id: 6, accountId: 'goal', description: 'Goal saving', amount: 100, date: '3 days ago', type: 'deposit' },
    { id: 7, accountId: 'emergency', description: 'Auto-save', amount: 20, date: '3 days ago', type: 'deposit' },
    { id: 8, accountId: 'daily', description: 'Round-up', amount: 5, date: '4 days ago', type: 'round-up' },
];

export const DISTRIBUTION_DATA: DistributionDataPoint[] = [
    { id: 'emergency', name: 'Emergency Fund', value: 4800, color: 'accent-mint', tooltipKey: 'save.chart.tooltip.emergency' },
    { id: 'daily', name: 'Daily Savings', value: 650, color: 'brand-saffron', tooltipKey: 'save.chart.tooltip.daily' },
    { id: 'spending', name: 'Spending', value: 3500, color: 'brand-purple', tooltipKey: 'save.chart.tooltip.spending' },
    { id: 'goals', name: 'Goals', value: 1200, color: 'soft-teal', tooltipKey: 'save.chart.tooltip.goals' },
    { id: 'bills', name: 'Bills', value: 1850, color: 'text-secondary', tooltipKey: 'save.chart.tooltip.bills' },
    { id: 'buffer', name: 'Cash Buffer', value: 500, color: 'cream', tooltipKey: 'save.chart.tooltip.buffer' },
];

// --- Claims Feature Data ---

const GENERAL_DOCS = [
    { key: 'claimForm', nameKey: 'claims.docs.claimForm' },
    { key: 'policyCopy', nameKey: 'claims.docs.policyCopy' },
    { key: 'photoId', nameKey: 'claims.docs.photoId' },
    { key: 'addressProof', nameKey: 'claims.docs.addressProof' },
    { key: 'bankDetails', nameKey: 'claims.docs.bankDetails' },
];

export const CLAIM_DOCUMENTS_MAP: PolicyClaimInfo[] = [
    {
        policyId: 1, // Daily Accident Cover
        scenarios: [
            { 
                key: 'injury', nameKey: 'claims.scenarios.accident.injury', 
                documents: [
                    ...GENERAL_DOCS,
                    { key: 'fir', nameKey: 'claims.docs.fir' },
                    { key: 'medicalRecords', nameKey: 'claims.docs.medicalRecords' },
                    { key: 'hospitalBills', nameKey: 'claims.docs.hospitalBills' },
                ]
            },
            { 
                key: 'disability', nameKey: 'claims.scenarios.accident.disability',
                documents: [
                    ...GENERAL_DOCS,
                    { key: 'fir', nameKey: 'claims.docs.fir' },
                    { key: 'medicalRecords', nameKey: 'claims.docs.medicalRecords' },
                    { key: 'disabilityCert', nameKey: 'claims.docs.disabilityCert' },
                    { key: 'mlc', nameKey: 'claims.docs.mlc' },
                ]
            },
            { 
                key: 'death', nameKey: 'claims.scenarios.accident.death',
                documents: [
                    ...GENERAL_DOCS,
                    { key: 'deathCert', nameKey: 'claims.docs.deathCert' },
                    { key: 'fir', nameKey: 'claims.docs.fir' },
                    { key: 'postMortem', nameKey: 'claims.docs.postMortem' },
                    { key: 'drivingLicense', nameKey: 'claims.docs.drivingLicense' },
                ]
            }
        ]
    },
    {
        policyId: 2, // Micro Health Floater
        documents: [
            ...GENERAL_DOCS,
            { key: 'doctorPrescription', nameKey: 'claims.docs.doctorPrescription' },
            { key: 'hospitalBills', nameKey: 'claims.docs.hospitalBills' },
            { key: 'dischargeSummary', nameKey: 'claims.docs.dischargeSummary' },
            { key: 'investigationReports', nameKey: 'claims.docs.investigationReports' },
            { key: 'pharmacyBills', nameKey: 'claims.docs.pharmacyBills' },
        ]
    },
    {
        policyId: 3, // Crop & Farming Risk
        documents: [
            { key: 'landRecords', nameKey: 'claims.docs.landRecords' },
            { key: 'policyCopy', nameKey: 'claims.docs.policyCopy' },
            { key: 'bankDetails', nameKey: 'claims.docs.bankDetails' },
            { key: 'lossIntimation', nameKey: 'claims.docs.lossIntimation' },
            { key: 'lossAssessment', nameKey: 'claims.docs.lossAssessment' },
            { key: 'photos', nameKey: 'claims.docs.photos' },
        ]
    },
    {
        policyId: 6, // Family Death / Income Replacement
        scenarios: [
            {
                key: 'natural', nameKey: 'claims.scenarios.death.natural',
                documents: [
                    ...GENERAL_DOCS,
                    { key: 'deathCert', nameKey: 'claims.docs.deathCert' },
                    { key: 'causeOfDeathCert', nameKey: 'claims.docs.causeOfDeathCert' },
                    { key: 'hospitalRecords', nameKey: 'claims.docs.hospitalRecords' },
                ]
            },
            {
                key: 'unnatural', nameKey: 'claims.scenarios.death.unnatural',
                documents: [
                     ...GENERAL_DOCS,
                    { key: 'deathCert', nameKey: 'claims.docs.deathCert' },
                    { key: 'fir', nameKey: 'claims.docs.fir' },
                    { key: 'postMortem', nameKey: 'claims.docs.postMortem' },
                ]
            }
        ]
    },
    {
        policyId: 8, // Small Business Public Liability
        documents: [
            { key: 'policyCopy', nameKey: 'claims.docs.policyCopy' },
            { key: 'incidentDescription', nameKey: 'claims.docs.incidentDescription' },
            { key: 'thirdPartyDetails', nameKey: 'claims.docs.thirdPartyDetails' },
            { key: 'fir', nameKey: 'claims.docs.fir' },
            { key: 'legalNotice', nameKey: 'claims.docs.legalNotice' },
            { key: 'witnessStatements', nameKey: 'claims.docs.witnessStatements' },
            { key: 'lossEstimate', nameKey: 'claims.docs.lossEstimate' },
        ]
    },
    {
        policyId: 9, // Senior Citizen Daily Cash
        documents: [
            ...GENERAL_DOCS,
            { key: 'dischargeSummary', nameKey: 'claims.docs.dischargeSummary' },
        ]
    },
];

export const GOVERNMENT_SCHEMES_IDS = Array.from({ length: 17 }, (_, i) => i + 1);

// --- Mock Data for Settings Screens ---

export const USER_POLICIES = [
  { id: 1, policyId: 1, policyNumber: 'N-AC-1002345', coverage: 200000, premium: 5, dueDate: '15 Jul 2024' },
  { id: 2, policyId: 2, policyNumber: 'N-HF-2334561', coverage: 100000, premium: 10, dueDate: '20 Jul 2024' },
  { id: 3, policyId: 8, policyNumber: 'N-BL-9876543', coverage: 50000, premium: 5, dueDate: '28 Jul 2024' },
];

export const USER_DOCUMENTS = [
  { id: 'aadhaar', nameKey: 'myDocuments.aadhaar', status: 'verified' },
  { id: 'pan', nameKey: 'myDocuments.pan', status: 'verified' },
  { id: 'drivingLicense', nameKey: 'myDocuments.drivingLicense', status: 'pending' },
  { id: 'rationCard', nameKey: 'myDocuments.rationCard', status: 'verified' },
];

export const UPI_MANDATES = [
  { id: 1, policyId: 1, amount: 5, upiApp: 'gpay' },
  { id: 2, policyId: 2, amount: 10, upiApp: 'phonepe' },
  { id: 3, policyId: 8, amount: 5, upiApp: 'paytm' },
];
